# Generated by Django 4.2.7 on 2023-11-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_priority_rename_datecompletd_task_datecompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.priority'),
        ),
    ]
