# Generated by Django 4.2.7 on 2023-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_states_task_completed_task_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
    ]
