# Generated by Django 4.2.7 on 2023-11-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_task_state_alter_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
