# Generated by Django 4.2.7 on 2023-11-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_task_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='TaskStates',
        ),
        migrations.RenameField(
            model_name='taskstates',
            old_name='state',
            new_name='task_state',
        ),
        migrations.AddField(
            model_name='task',
            name='task_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taskstates'),
        ),
    ]
