# Generated by Django 4.2.7 on 2023-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_taskstates_taskcondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_state',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='TaskCondition',
        ),
    ]
