# Generated by Django 4.2.7 on 2023-11-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_task_task_state_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
