# Generated by Django 4.2.7 on 2023-11-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taskcondition'),
        ),
    ]
